<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EquipmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('equipment')->insert([
            [
                'id' => 1,
                'number' => '2150-2200-067-27-3-4(10)',
                'name' => 'จอรับภาพแบบมือดึง  4  จอยี่ห้อ  Razr  รุ่น WMW  ขนาดจอ 120 นิ้ว (วัดตามเส้นทแยงมุม) เนื้อจอสีขาว ทำจากFiber ชนิด Matt White กระบอกจอและฝาปิดทั้งสองข้างทำด้วยเหล็กหนา',
                'amount' => 10,
                'price' => 4815.00,
                'total_price' => 48150.00,
                'status_found' => 5,
                'status_not_found' => 0,
                'status_broken' => 0,
                'status_disposal' => 0,
                'status_transfer' => 5,
                'equipment_unit_id' => 1,
                'location_id' => 1,
                'title_id' => 1,
                'user_id' => null,
                'description' => null,
                'original_image_name' => 'image-1.jpg',
                'stored_image_name' => 'image-1.jpg',
                'is_locked' => 1,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 12:54:51',
                'updated_at' => '2025-09-25 13:00:24',
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'number' => '2151-2234013-060-03-7-50',
                'name' => '1.เครื่องคอมพิวเตอร์ 50 เครื่อง มี Slot หรือ Socket Processor Intel Core 2 Extreme DDR2 RAM ความเร็ว 800 MHz ขนาด 1024 MB ประมวลผลกลางของ Intel Core 2Duo E6550 Processor จอภาพ 17 นิ้ว LCD',
                'amount' => 29,
                'price' => null,
                'total_price' => null,
                'status_found' => 10,
                'status_not_found' => 4,
                'status_broken' => 15,
                'status_disposal' => 5,
                'status_transfer' => 0,
                'equipment_unit_id' => 3,
                'location_id' => 3,
                'title_id' => 1,
                'user_id' => null,
                'description' => null,
                'original_image_name' => 'image-2.jpg',
                'stored_image_name' => 'image-2.jpg',
                'is_locked' => 1,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 12:54:51',
                'updated_at' => '2025-09-25 13:00:24',
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'number' => '2151-2234013-060-02-1-1',
                'name' => '6.คอมพิวเตอร์แม่ข่าย 1 เครื่อง ยี่ห้อ IBM รุ่น Xseries 3400 จอภาพ 17 นิ้ว LCD',
                'amount' => 10,
                'price' => null,
                'total_price' => 0.00,
                'status_found' => 7,
                'status_not_found' => 0,
                'status_broken' => 3,
                'status_disposal' => 3,
                'status_transfer' => 0,
                'equipment_unit_id' => 3,
                'location_id' => 1,
                'title_id' => 1,
                'user_id' => null,
                'description' => null,
                'original_image_name' => 'image-3.jpg',
                'stored_image_name' => 'image-3.jpg',
                'is_locked' => 1,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 12:54:51',
                'updated_at' => '2025-09-25 13:00:24',
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'number' => '2150-2200-067-27-3-4(10)',
                'name' => 'จอรับภาพแบบมือดึง  4  จอยี่ห้อ  Razr  รุ่น WMW  ขนาดจอ 120 นิ้ว (วัดตามเส้นทแยงมุม) เนื้อจอสีขาว ทำจากFiber ชนิด Matt White กระบอกจอและฝาปิดทั้งสองข้างทำด้วยเหล็กหนา',
                'amount' => 5,
                'price' => 4815.00,
                'total_price' => 48150.00,
                'status_found' => 5,
                'status_not_found' => 0,
                'status_broken' => 0,
                'status_disposal' => 0,
                'status_transfer' => 0,
                'equipment_unit_id' => 8,
                'location_id' => 8,
                'title_id' => 2,
                'user_id' => null,
                'description' => null,
                'original_image_name' => 'image-1.jpg',
                'stored_image_name' => 'image-4.jpg',
                'is_locked' => 1,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 12:54:51',
                'updated_at' => '2025-09-25 13:01:40',
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'number' => '2151-2234013-060-03-7-50',
                'name' => '1.เครื่องคอมพิวเตอร์ 50 เครื่อง มี Slot หรือ Socket Processor Intel Core 2 Extreme DDR2 RAM ความเร็ว 800 MHz ขนาด 1024 MB ประมวลผลกลางของ Intel Core 2Duo E6550 Processor จอภาพ 17 นิ้ว LCD',
                'amount' => 20,
                'price' => null,
                'total_price' => 0.00,
                'status_found' => 15,
                'status_not_found' => 2,
                'status_broken' => 3,
                'status_disposal' => 3,
                'status_transfer' => 0,
                'equipment_unit_id' => 10,
                'location_id' => 7,
                'title_id' => 2,
                'user_id' => null,
                'description' => null,
                'original_image_name' => 'image-2.jpg',
                'stored_image_name' => 'image-5.jpg',
                'is_locked' => 1,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 12:54:51',
                'updated_at' => '2025-09-25 13:01:40',
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'number' => '2151-2234013-060-02-1-1',
                'name' => '6.คอมพิวเตอร์แม่ข่าย 1 เครื่อง ยี่ห้อ IBM รุ่น Xseries 3400 จอภาพ 17 นิ้ว LCD',
                'amount' => 7,
                'price' => null,
                'total_price' => 0.00,
                'status_found' => 4,
                'status_not_found' => 0,
                'status_broken' => 0,
                'status_disposal' => 0,
                'status_transfer' => 3,
                'equipment_unit_id' => 10,
                'location_id' => 8,
                'title_id' => 2,
                'user_id' => null,
                'description' => null,
                'original_image_name' => 'image-3.jpg',
                'stored_image_name' => 'image-6.jpg',
                'is_locked' => 1,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 12:54:51',
                'updated_at' => '2025-09-25 13:01:40',
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'number' => '2150-2200-067-27-3-4(10)',
                'name' => 'จอรับภาพแบบมือดึง  4  จอยี่ห้อ  Razr  รุ่น WMW  ขนาดจอ 120 นิ้ว (วัดตามเส้นทแยงมุม) เนื้อจอสีขาว ทำจากFiber ชนิด Matt White กระบอกจอและฝาปิดทั้งสองข้างทำด้วยเหล็กหนา',
                'amount' => 5,
                'price' => 4815.00,
                'total_price' => 24075.00,
                'status_found' => 5,
                'status_not_found' => 0,
                'status_broken' => 0,
                'status_disposal' => 0,
                'status_transfer' => 0,
                'equipment_unit_id' => 1,
                'location_id' => null,
                'title_id' => 3,
                'user_id' => 7,
                'description' => null,
                'original_image_name' => 'image-1.jpg',
                'stored_image_name' => 'image-7.jpg',
                'is_locked' => 1,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 12:54:51',
                'updated_at' => '2025-09-25 13:26:39',
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'number' => '2151-2234013-060-03-7-50',
                'name' => '1.เครื่องคอมพิวเตอร์ 50 เครื่อง มี Slot หรือ Socket Processor Intel Core 2 Extreme DDR2 RAM ความเร็ว 800 MHz ขนาด 1024 MB ประมวลผลกลางของ Intel Core 2Duo E6550 Processor จอภาพ 17 นิ้ว LCD',
                'amount' => 15,
                'price' => null,
                'total_price' => 0.00,
                'status_found' => 4,
                'status_not_found' => 0,
                'status_broken' => 11,
                'status_disposal' => 11,
                'status_transfer' => 0,
                'equipment_unit_id' => 13,
                'location_id' => 10,
                'title_id' => 3,
                'user_id' => null,
                'description' => null,
                'original_image_name' => 'image-2.jpg',
                'stored_image_name' => 'image-8.jpg',
                'is_locked' => 1,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 12:54:51',
                'updated_at' => '2025-09-25 13:26:39',
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'number' => '2151-2234013-060-02-1-1',
                'name' => '6.คอมพิวเตอร์แม่ข่าย 1 เครื่อง ยี่ห้อ IBM รุ่น Xseries 3400 จอภาพ 17 นิ้ว LCD',
                'amount' => 4,
                'price' => null,
                'total_price' => 0.00,
                'status_found' => 1,
                'status_not_found' => 0,
                'status_broken' => 0,
                'status_disposal' => 0,
                'status_transfer' => 3,
                'equipment_unit_id' => 13,
                'location_id' => 11,
                'title_id' => 3,
                'user_id' => null,
                'description' => null,
                'original_image_name' => 'image-3.jpg',
                'stored_image_name' => 'image-9.jpg',
                'is_locked' => 1,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 12:54:51',
                'updated_at' => '2025-09-25 13:26:39',
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'number' => '2150-2200-067-27-3-4(10)',
                'name' => 'จอรับภาพแบบมือดึง  4  จอยี่ห้อ  Razr  รุ่น WMW  ขนาดจอ 120 นิ้ว (วัดตามเส้นทแยงมุม) เนื้อจอสีขาว ทำจากFiber ชนิด Matt White กระบอกจอและฝาปิดทั้งสองข้างทำด้วยเหล็กหนา',
                'amount' => 5,
                'price' => 4815.00,
                'total_price' => 24075.00,
                'status_found' => 0,
                'status_not_found' => 0,
                'status_broken' => 0,
                'status_disposal' => 0,
                'status_transfer' => 0,
                'equipment_unit_id' => 14,
                'location_id' => null,
                'title_id' => 4,
                'user_id' => 4,
                'description' => null,
                'original_image_name' => 'image-1.jpg',
                'stored_image_name' => 'image-10.jpg',
                'is_locked' => 0,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 12:54:51',
                'updated_at' => '2025-09-25 13:24:10',
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'number' => '2151-2234013-060-03-7-50',
                'name' => '1.เครื่องคอมพิวเตอร์ 50 เครื่อง มี Slot หรือ Socket Processor Intel Core 2 Extreme DDR2 RAM ความเร็ว 800 MHz ขนาด 1024 MB ประมวลผลกลางของ Intel Core 2Duo E6550 Processor จอภาพ 17 นิ้ว LCD',
                'amount' => 4,
                'price' => null,
                'total_price' => 0.00,
                'status_found' => 0,
                'status_not_found' => 0,
                'status_broken' => 0,
                'status_disposal' => 0,
                'status_transfer' => 0,
                'equipment_unit_id' => 16,
                'location_id' => 12,
                'title_id' => 4,
                'user_id' => null,
                'description' => null,
                'original_image_name' => 'image-2.jpg',
                'stored_image_name' => 'image-11.jpg',
                'is_locked' => 0,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 12:54:51',
                'updated_at' => '2025-09-25 13:02:49',
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'number' => '2151-2234013-060-02-1-1',
                'name' => '6.คอมพิวเตอร์แม่ข่าย 1 เครื่อง ยี่ห้อ IBM รุ่น Xseries 3400 จอภาพ 17 นิ้ว LCD',
                'amount' => 1,
                'price' => null,
                'total_price' => 0.00,
                'status_found' => 0,
                'status_not_found' => 0,
                'status_broken' => 0,
                'status_disposal' => 0,
                'status_transfer' => 0,
                'equipment_unit_id' => 16,
                'location_id' => 13,
                'title_id' => 4,
                'user_id' => null,
                'description' => null,
                'original_image_name' => 'image-3.jpg',
                'stored_image_name' => 'image-12.jpg',
                'is_locked' => 0,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 12:54:51',
                'updated_at' => '2025-09-25 13:02:49',
                'deleted_at' => null,
            ],
        ]);
    }
}
