<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EquipmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('equipment')->insert([
            [
                'number' => '2150-2200-067-27-3-4(10)',
                'name' => 'จอรับภาพแบบมือดึง  4  จอยี่ห้อ  Razr  รุ่น WMW  ขนาดจอ 120 นิ้ว (วัดตามเส้นทแยงมุม) เนื้อจอสีขาว ทำจากFiber ชนิด Matt White กระบอกจอและฝาปิดทั้งสองข้างทำด้วยเหล็กหนา',
                'amount' => 1,
                'price' => 4815.00,
                'total_price' => 4815.00,
                'status' => 'พบ',
                'group' => 1,
                'equipment_unit_id' => 1,
                'location_id' => 1,
                'equipment_type_id' => null,
                'title_id' => 1,
                'user_id' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2151-2234013-060-03-7-50',
                'name' => '1.เครื่องคอมพิวเตอร์ 50 เครื่อง มี Slot หรือ Socket Processor Intel Core 2 Extreme DDR2 RAM ความเร็ว 800 MHz ขนาด 1024 MB ประมวลผลกลางของ Intel Core 2Duo E6550 Processor จอภาพ 17 นิ้ว LCD',
                'amount' => 29,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 2,
                'equipment_unit_id' => 3,
                'location_id' => null,
                'equipment_type_id' => 1,
                'title_id' => 1,
                'user_id' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2151-2234013-060-02-1-1',
                'name' => '6.คอมพิวเตอร์แม่ข่าย 1 เครื่อง ยี่ห้อ IBM รุ่น Xseries 3400 จอภาพ 17 นิ้ว LCD',
                'amount' => 1,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 3,
                'equipment_unit_id' => 3,
                'location_id' => 2,
                'equipment_type_id' => 1,
                'title_id' => 1,
                'user_id' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2151-2234013-060-77-1-2',
                'name' => '7.อุปกรณ์กระจายสัญญาณแบบไร้สาย 2 เครื่อง ยี่ห้อ Zyxel รุ่น P-660HW ความเร็วในการรับส่งข้อมูล 54 Mbps',
                'amount' => 2,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 4,
                'equipment_unit_id' => 3,
                'location_id' => null,
                'equipment_type_id' => 1,
                'title_id' => 1,
                'user_id' => 4,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2151-2234013-060-77-1-1(2)',
                'name' => '7.อุปกรณ์กระจายสัญญาณแบบไร้สาย 2 เครื่อง ยี่ห้อ Zyxel รุ่น P-660HW ความเร็วในการรับส่งข้อมูล 54 Mbps',
                'amount' => 1,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 4.01,
                'equipment_unit_id' => '3',
                'location_id' => null,
                'equipment_type_id' => 1,
                'title_id' => 1,
                'user_id' => 4,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2151-2234013-060-77-1-2(2)',
                'name' => '7.อุปกรณ์กระจายสัญญาณแบบไร้สาย 2 เครื่อง ยี่ห้อ Zyxel รุ่น P-660HW ความเร็วในการรับส่งข้อมูล 54 Mbps',
                'amount' => 1,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 4.02,
                'equipment_unit_id' => 3,
                'location_id' => null,
                'equipment_type_id' => 1,
                'title_id' => 1,
                'user_id' => 4,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2151-2234013-060-70-1-1',
                'name' => '8.อุปกรณ์การค้นหาเส้นทางของข้อมูล 1 ค.ยี่ห้อ 3Com รุ่น 5012 ขนาด 19 นิ้วS/N:9HGF9BKF3771F ',
                'amount' => 1,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 7,
                'equipment_unit_id' => 3,
                'location_id' => 2,
                'equipment_type_id' => 1,
                'title_id' => 1,
                'user_id' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2151-2234013-060-89-1-1',
                'name' => '9.ตู้ RACK ขนาด 19 นิ้ว 1 ตู้',
                'amount' => 1,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 8,
                'equipment_unit_id' => 4,
                'location_id' => 4,
                'equipment_type_id' => 1,
                'title_id' => 1,
                'user_id' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2151-2234013-060-101-1-17',
                'name' => '10.ชุดปฏิบัติการออกแบบวงจรดิจิตอล DDT-1 รุ่น DL-2001 S/N:0857030-085739,085741,085746,085726   แทง 58  = 7 ตัว   คงเหลือ  10  ตัว',
                'amount' => 10,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 9,
                'equipment_unit_id' => 5,
                'location_id' => 5,
                'equipment_type_id' => 1,
                'title_id' => 1,
                'user_id' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2151-2234013-060-104-1-17',
                'name' => '11.ชุดฝึกปฏิบัติการออกแบบระบบตัวเชื่อมประสาน 17 ชุด ETT รุ่น ET-LAB3A V6.0',
                'amount' => 17,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 10,
                'equipment_unit_id' => 6,
                'location_id' => 5,
                'equipment_type_id' => 1,
                'title_id' => 1,
                'user_id' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2151-2234013-060-47-1-17',
                'name' => '12.ชุดทดลองอินเตอร์เฟส (ET-LAB3A)',
                'amount' => 17,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 11,
                'equipment_unit_id' => 6,
                'location_id' => null,
                'equipment_type_id' => 1,
                'title_id' => 1,
                'user_id' => null,
                'description' => '1-16 อท.50117 อ.วาทการ',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2151-2234013-067-31-1-1',
                'name' => '13.บอร์ดแสดงผลอักษรไฟวิ่ง 1 ชุดTri-color Dot Matris LED Moving SigeBoard รุ่น MC16x240',
                'amount' => 1,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 12,
                'equipment_unit_id' => 7,
                'location_id' => 6,
                'equipment_type_id' => 1,
                'title_id' => 1,
                'user_id' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2151-2234013-071-110-1-19',
                'name' => '15.ประกอบด้วยโต๊ะ',
                'amount' => 19,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 13,
                'equipment_unit_id' => 5,
                'location_id' => 7,
                'equipment_type_id' => 1,
                'title_id' => 1,
                'user_id' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2151-2234013-071-131-1-40',
                'name' => 'และเก้าอี้ปฏิบัติการ',
                'amount' => 38,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 14,
                'equipment_unit_id' => 5,
                'location_id' => 7,
                'equipment_type_id' => 1,
                'title_id' => 1,
                'user_id' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2151-2234013-071-55-1-12',
                'name' => '18.ตู้สำหรับจัดเก็บชุดฝึกปฏิบัติการ 12 ตู้ เป็นตู้บานเลื่อน 4 ฟุต ทำจากโลหะพร้อมกุญแจล็อค',
                'amount' => 12,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 15,
                'equipment_unit_id' => 4,
                'location_id' => null,
                'equipment_type_id' => 1,
                'title_id' => 1,
                'user_id' => null,
                'description' => '3,5,8 อท 5012,4,6 อท 5021 อท 5037,9 อท 50911,12 สนง',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2151-2234013-060-17-1-17',
                'name' => '21.ไมโครโปรเซสเซอร์แผงวงจรเดี่ยว Z-8017 ชุด ชุด TRIANING BOARD "ETT" รุ่น ET-BOARD V6.0',
                'amount' => 17,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 16,
                'equipment_unit_id' => 6,
                'location_id' => 5,
                'equipment_type_id' => 1,
                'title_id' => 1,
                'user_id' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2151-2234013-059-85-1-10',
                'name' => '22.เครื่องวัดสัญญาณไฟฟ้า 10 เครื่องยี่ห้อ RIGOL รุ่น DS1024CDS/N:DS1042000000654 ,DS1042000000675 , DS1042000000660 ,DS1042000000644 ,',
                'amount' => 10,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 17,
                'equipment_unit_id' => 3,
                'location_id' => null,
                'equipment_type_id' => 1,
                'title_id' => 1,
                'user_id' => null,
                'description' => '1,3-10 อท.5012(10)',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2151-2234013-059-185-1-4',
                'name' => '23.แหล่งจ่ายไฟฟ้ากระแสตรงปรับค่าได้ 4 เครื่อง ยี่ห้อ GW Instek รุ่น GPS-3030DDS/N : EH922246 , EH922287 , EH922255',
                'amount' => 4,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 18,
                'equipment_unit_id' => 3,
                'location_id' => null,
                'equipment_type_id' => 1,
                'title_id' => 1,
                'user_id' => null,
                'description' => '1 (4) ห้องเก็บของ2 (4) อ.วาทการ3 (4) อท.5024 (4) อ.นราศักดิ์',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2161-2234-059-301-1(20)-20(20)',
                'name' => '3.แหล่งจ่ายไฟฟ้ากระแสตรงปรับค่าได้',
                'amount' => 20,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 19,
                'equipment_unit_id' => 6,
                'location_id' => 8,
                'equipment_type_id' => 2,
                'title_id' => 2,
                'user_id' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2161-2234-059-068-51(20)-70(20)',
                'name' => '4.ชุดทดลองการออกแบบวงจรดิจิตอลด้วย FPGA',
                'amount' => 20,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 20,
                'equipment_unit_id' => 6,
                'location_id' => 8,
                'equipment_type_id' => 2,
                'title_id' => 2,
                'user_id' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2161-2234-059-068-31(20)-50(20)',
                'name' => '5.ชุดทดลองการออกแบบวงจรดิจิตอลด้วย CPLD',
                'amount' => 20,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 21,
                'equipment_unit_id' => 6,
                'location_id' => 8,
                'equipment_type_id' => 2,
                'title_id' => 2,
                'user_id' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2161-2234-059-068-1(30)-30(30)',
                'name' => '6.ชุดทดลองการออกแบบวงจรดิจิตอล',
                'amount' => 30,
                'price' => null,
                'total_price' => null,
                'status' => 'พบ',
                'group' => 22,
                'equipment_unit_id' => 6,
                'location_id' => 8,
                'equipment_type_id' => 2,
                'title_id' => 2,
                'user_id' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => '2359-2234-060-160-1(1)',
                'name' => 'เครื่องพิมพ์แบบ All in one ยี่ห้อ EPSON รุ่น L455 + INK TANK',
                'amount' => 1,
                'price' => 8500.00,
                'total_price' => 8500.00,
                'status' => 'พบ',
                'group' => 23,
                'equipment_unit_id' => 3,
                'location_id' => 9,
                'equipment_type_id' => null,
                'title_id' => 2,
                'user_id' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => 'testingnumber1',
                'name' => 'testingequipment1',
                'amount' => 1,
                'price' => 8500.00,
                'total_price' => 8500.00,
                'status' => 'โอน',
                'group' => 24,
                'equipment_unit_id' => 3,
                'location_id' => 9,
                'equipment_type_id' => null,
                'title_id' => 2,
                'user_id' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => 'testingnumber2',
                'name' => 'testingequipment2',
                'amount' => 1,
                'price' => 8500.00,
                'total_price' => 8500.00,
                'status' => 'แทงจำหน่าย',
                'group' => 25,
                'equipment_unit_id' => 3,
                'location_id' => 9,
                'equipment_type_id' => null,
                'title_id' => 2,
                'user_id' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'number' => 'testingnumber3',
                'name' => 'testingequipment3',
                'amount' => 1,
                'price' => 8500.00,
                'total_price' => 8500.00,
                'status' => 'ชำรุด',
                'group' => 26,
                'equipment_unit_id' => 3,
                'location_id' => 9,
                'equipment_type_id' => null,
                'title_id' => 2,
                'user_id' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ]);
    }
}
