<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Equipment_unitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('equipment_units')->insert([
            [
                'id' => 1,
                'name' => 'จ.1/1/50 จอ',
                'is_locked' => 0,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 12:54:50',
                'updated_at' => '2025-09-25 12:54:50',
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'จ.1/12/51',
                'is_locked' => 0,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 12:54:50',
                'updated_at' => '2025-09-25 12:54:50',
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'เครื่อง',
                'is_locked' => 0,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 12:54:50',
                'updated_at' => '2025-09-25 12:54:50',
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'name' => 'ตู้',
                'is_locked' => 0,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 12:54:50',
                'updated_at' => '2025-09-25 12:54:50',
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'name' => 'ตัว',
                'is_locked' => 0,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 12:54:50',
                'updated_at' => '2025-09-25 12:54:50',
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'name' => 'ชุด',
                'is_locked' => 0,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 12:54:50',
                'updated_at' => '2025-09-25 12:54:50',
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'name' => 'บอร์ด',
                'is_locked' => 0,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 12:54:50',
                'updated_at' => '2025-09-25 12:54:50',
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'name' => 'จ.1/1/50 จอ',
                'is_locked' => 1,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 13:00:24',
                'updated_at' => '2025-09-25 13:00:24',
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'name' => 'เครื่อง',
                'is_locked' => 1,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 13:00:24',
                'updated_at' => '2025-09-25 13:00:24',
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'name' => 'เครื่อง',
                'is_locked' => 1,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 13:00:24',
                'updated_at' => '2025-09-25 13:00:24',
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'name' => 'จ.1/1/50 จอ',
                'is_locked' => 1,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 13:01:40',
                'updated_at' => '2025-09-25 13:01:40',
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'name' => 'เครื่อง',
                'is_locked' => 1,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 13:01:40',
                'updated_at' => '2025-09-25 13:01:40',
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'name' => 'เครื่อง',
                'is_locked' => 1,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 13:01:40',
                'updated_at' => '2025-09-25 13:01:40',
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'name' => 'จ.1/1/50 จอ',
                'is_locked' => 1,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 13:26:39',
                'updated_at' => '2025-09-25 13:26:39',
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'name' => 'เครื่อง',
                'is_locked' => 1,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 13:26:39',
                'updated_at' => '2025-09-25 13:26:39',
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'name' => 'เครื่อง',
                'is_locked' => 1,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 13:26:39',
                'updated_at' => '2025-09-25 13:26:39',
                'deleted_at' => null,
            ],
        ]);
    }
}
