version: 1
services:
  - type: web
    name: equipment2
    env: php
    plan: free
    buildCommand: "composer install --no-interaction"
    startCommand: "php artisan serve --host=0.0.0.0 --port=80"
    envVars:
      - key: DB_CONNECTION
        value: "pgsql"
      - key: DB_HOST
        value: "equipment3.postgres.render.com"  # Host ของ PostgreSQL ที่ให้บริการ
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: "equipment2"
      - key: DB_USERNAME
        value: "Acer"  # ชื่อผู้ใช้ที่คุณตั้งใน Render
      - key: DB_PASSWORD
        value: "123456"  # รหัสผ่านที่ถูกต้อง
      - key: APP_KEY
        value: "base64:pGLIQsNIeMiXWHvBlpziRXZn+p03KmJHxMv4q6G//LA="  # ถ้าจำเป็น
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://equipment2.onrender.com"  # ถ้าต้องการกำหนด URL ของแอปในโปรดักชั่น
