<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    protected static ?string $password;

    public function run(): void
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'username' => 'Sakchan',
                'prefix_id' => 8,
                'firstname' => 'ศักดิ์ชาญ',
                'lastname' => 'เหลืองมณีโรจน์',
                'user_type' => 'ผู้ดูแลระบบ',
                'password' => static::$password ??= Hash::make('password'),
                'remember_token' => Str::random(10),
                'last_login_at' => '2025-09-25 13:23:57',
                'is_locked' => 0,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => null,
                'updated_at' => '2025-09-25 13:23:57',
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'username' => 'Suchetta',
                'prefix_id' => 1,
                'firstname' => 'สุเชษฐา',
                'lastname' => 'พรหมประเสริฐ',
                'user_type' => 'เจ้าหน้าที่พัสดุ',
                'password' => static::$password ??= Hash::make('password'),
                'remember_token' => Str::random(10),
                'last_login_at' => null,
                'is_locked' => 0,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'username' => 'Suhunsa',
                'prefix_id' => 2,
                'firstname' => 'สุหรรษา',
                'lastname' => 'ใจหนึ่ง',
                'user_type' => 'ผู้ปฏิบัติงานบริหาร',
                'password' => static::$password ??= Hash::make('password'),
                'remember_token' => Str::random(10),
                'last_login_at' => '2025-09-25 13:08:35',
                'is_locked' => 0,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => null,
                'updated_at' => '2025-09-25 13:08:35',
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'username' => 'Boonlueo',
                'prefix_id' => 4,
                'firstname' => 'บุญเหลือ',
                'lastname' => 'นาบำรุง',
                'user_type' => 'ผู้ดูแลครุภัณฑ์',
                'password' => static::$password ??= Hash::make('password'),
                'remember_token' => Str::random(10),
                'last_login_at' => null,
                'is_locked' => 0,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'username' => 'Narasuk',
                'prefix_id' => 7,
                'firstname' => 'นราศักดิ์',
                'lastname' => 'วงษ์วาสน์',
                'user_type' => 'ผู้ดูแลครุภัณฑ์',
                'password' => static::$password ??= Hash::make('password'),
                'remember_token' => Str::random(10),
                'last_login_at' => null,
                'is_locked' => 0,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'username' => 'user1',
                'prefix_id' => 1,
                'firstname' => 'กิตติศักดิ์',
                'lastname' => 'ผาทอง',
                'user_type' => 'ผู้ดูแลระบบ',
                'password' => static::$password ??= Hash::make('password'),
                'remember_token' => Str::random(10),
                'last_login_at' => null,
                'is_locked' => 0,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'username' => 'Nipon',
                'prefix_id' => 4,
                'firstname' => 'นิพนธ์',
                'lastname' => 'พิมพ์เบ้าธรรม',
                'user_type' => 'ผู้ดูแลครุภัณฑ์',
                'password' => static::$password ??= Hash::make('password'),
                'remember_token' => Str::random(10),
                'last_login_at' => null,
                'is_locked' => 0,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 13:26:39',
                'updated_at' => '2025-09-25 13:26:39',
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'username' => 'Tongme',
                'prefix_id' => 4,
                'firstname' => 'ทองมี',
                'lastname' => 'ละครพล',
                'user_type' => 'ผู้ดูแลครุภัณฑ์',
                'password' => static::$password ??= Hash::make('password'),
                'remember_token' => Str::random(10),
                'last_login_at' => null,
                'is_locked' => 0,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => '2025-09-25 13:26:39',
                'updated_at' => '2025-09-25 13:26:39',
                'deleted_at' => null,
            ],
        ]);
    }
}
